alis_crm/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from django.contrib import admin

from sales.routing import websocket_urlpatterns
from sales.views import index


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('ws/', include(websocket_urlpatterns)),
    path('admin/', admin.site.urls),
    path('debug/', include('debug_toolbar.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]


urlpatterns += i18n_patterns(
    path('', index, name='index'),
    path('task/', include('task.urls', namespace='task')),
    path('sales/', include('sales.urls', namespace='sale')),


)

sales/urls.py
from django.urls import path, re_path

from sales import consumers
from sales.views import OrderListView, OrderCreateView, projection_view

app_name = 'sales'

urlpatterns = [
    path("orders/", OrderListView.as_view(), name="order_list"),
    path('orders/create/', OrderCreateView.as_view(), name='order_create'),
    path("projection/", projection_view, name="projection"),
]

task/urls.py
from django.urls import path
from . import views
from .views import CalendarView, EventCreateView, EventDetailView, EventUpdateView, EventDeleteView

urlpatterns = [
    path('calendar/', CalendarView.as_view(), name='calendar'),
    path('create_event/', EventCreateView.as_view(), name='create_event'),
    path('event/<int:pk>/', EventDetailView.as_view(), name='event_detail'),
    path('event/<int:pk>/edit/', EventUpdateView.as_view(), name='event_edit'),
    path('event/<int:pk>/delete/', EventDeleteView.as_view(), name='event_delete'),

]

app_name = 'task'

sales/models.py
from datetime import timedelta

from django.core.exceptions import ValidationError
from django.db import models
from django.utils.timezone import now

from constants import ORDER_STATUSES, PRODUCTION_STATUS, REASONS, SALUT
from stock.models import Product


class Contact(models.Model):
    salutation = models.CharField(max_length=100, choices=SALUT, null=True, blank=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    phone = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    position = models.CharField(max_length=100, null=True, blank=True)


class Customer(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)

    def __str__(self):
        return self.name

    def clean(self):
        if not self.phone and not self.email:
            raise ValidationError("Either phone or email must be set.")

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)


class Company(models.Model):
    name = models.CharField(max_length=100)
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    email = models.EmailField(null=True, blank=True)
    delivery_address = models.CharField(max_length=255)
    invoice_address = models.CharField(max_length=255)
    tax_number = models.CharField(max_length=255, null=True, blank=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Companies"

    def __str__(self):
        return self.name


class Order(models.Model):
    number = models.CharField(max_length=25, unique=True, blank=True)
    status = models.CharField(max_length=25, choices=ORDER_STATUSES)
    production_status = models.CharField(max_length=25, choices=PRODUCTION_STATUS, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateField()
    internal_deadline = models.DateField(blank=True, null=True)
    updated_at = models.DateField(auto_now=True)
    partner = models.ForeignKey(Company, on_delete=models.CASCADE, blank=True, null=True)
    end_user = models.CharField(max_length=50, blank=True, null=True)
    direct_customer = models.ForeignKey(Customer, on_delete=models.CASCADE, blank=True, null=True)
    on_hold_reason = models.CharField(max_length=25, blank=True, null=True, choices=REASONS)

    def __str__(self):
        return self.number

    def save(self, *args, **kwargs):
        if not self.number:
            current_year = now().year
            last_two_digits = str(current_year)[-2:]
            prefix = f"Z{last_two_digits}"

            last_order = Order.objects.filter(number__startswith=prefix).order_by('-number').first()
            if last_order:
                last_number = int(last_order.number[-5:])
                new_number = last_number + 1
            else:
                new_number = 1

            self.number = f"{prefix}{new_number:05d}"

        if self.deadline and not self.internal_deadline:
            self.internal_deadline = self.deadline - timedelta(weeks=1)

        if self.status == "ON_HOLD" and not self.on_hold_reason:
            raise ValidationError("Reason must be provided if status is 'On hold'.")

        if not self.partner and not self.direct_customer:
            raise ValidationError('Either a partner or a direct customer must be set.')
        if self.partner and self.direct_customer:
            raise ValidationError('Both partner and direct customer cannot be set simultaneously.')

        super().save(*args, **kwargs)


class Cart(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    direct = models.ImageField(default=1)

    class Meta:
        ordering = ("product",)

    def __str__(self):
        return f"{self.order}: {self.product} - {self.quantity}"

sales/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields["on_hold_reason"].required = False
        if self.instance and self.instance.status == "ON_HOLD":
            self.fields["on_hold_reason"].required = True

    def clean(self):
        cleaned_data = super().clean()
        status = cleaned_data.get("status")
        on_hold_reason = cleaned_data.get("on_hold_reason")

        if status == "ON_HOLD" and not on_hold_reason:
            self.add_error(
                "on_hold_reason", 
                "Reason must be provided if status is ON_HOLD."
            )

        return cleaned_data


class OrderAdminForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = "__all__"
        exclude = ["number"]

    def clean(self):
        cleaned_data = super().clean()
        status = cleaned_data.get("production_status")
        on_hold_reason = cleaned_data.get("on_hold_reason")

        if status == "ON_HOLD" and not on_hold_reason:
            self.add_error(
                "on_hold_reason",
                'Reason must be provided if status is "On hold".')
        elif status != "ON_HOLD" and on_hold_reason:
            self.add_error(
                "on_hold_reason",
                'On hold reason can not be chosen when status is not "ON HOLD".'
            )


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['status', 'production_status', 'deadline', 'internal_deadline', 'partner', 'end_user', 'direct_customer', 'on_hold_reason']

sales/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy

from django.views.generic import CreateView, ListView

from chat.forms import ChatCreateForm, MessageForm
from chat.models import Message
from sales.forms import OrderCreateForm
from sales.models import Order
from task.models import Task, Event
from user.models import User


@login_required
def index(request: HttpRequest) -> HttpResponse:
    form = ChatCreateForm()
    user = User.objects.get(id=request.user.id)
    tasks = Task.objects.filter(executor=user)
    events = Event.objects.all()
    context = {
        "form": form,
        "tasks": tasks,
        'events': events
    }
    return render(request, "layouts/index.html", context)


class OrderListView(LoginRequiredMixin, ListView):
    model = Order
    paginate_by = 20
    context_object_name = 'orders'

    def get_queryset(self):
        search_query = self.request.GET.get('search', '')
        if search_query:
            return Order.objects.filter(Q(number__icontains=search_query))
        return Order.objects.all()


class OrderCreateView(LoginRequiredMixin, CreateView):
    model = Order
    form_class = OrderCreateForm
    success_url = reverse_lazy('sale:order_list')


def projection_view(request):
    return render(request, 'projector/projector_index.html')


# class MessageCreateView(LoginRequiredMixin, generic.CreateView):
#     model = Message
#     form_class = MessageForm
#     template_name = "task_manager/task/task_detail.html"
#
#     def form_valid(self, form: MessageForm) -> HttpResponse:
#         author_pk = self.kwargs.get("pk_author")
#         task_pk = self.kwargs.get("pk_task")
#
#         user = get_object_or_404(User, pk=author_pk)
#         task = get_object_or_404(Task, pk=task_pk)
#
#         form.instance.author = user
#         form.instance.task = task
#         return super().form_valid(form)
#
#     def get_success_url(self):
#         task_pk = self.kwargs.get("pk_task")
#         return reverse_lazy("task:task_detail", args=[task_pk])
#
#
# class MessageDeleteView(LoginRequiredMixin, generic.UpdateView):
#     def get(self, request, *args, **kwargs):
#         task_pk = self.kwargs.get("task_pk")
#         message_pk = self.kwargs.get("message_pk")
#         message = get_object_or_404(Message, pk=message_pk)
#         message.delete()
#         return HttpResponseRedirect(
#             reverse_lazy("task:task_detail", args=[task_pk])
#         )
#
#
# class ChatCreateView(LoginRequiredMixin, generic.CreateView):
#     model = Task
#     form_class = MessageForm
#
#     def post(self, request, *args, **kwargs):
#         task_id = request.POST.get("task")
#         return HttpResponseRedirect(
#             reverse_lazy("task:task_detail", args=[task_id])
#         )

templates/sales/order_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="container">
    <h2 class="mt-5">Create Order</h2>
    <form method="post" enctype="multipart/form-data" class="mt-3" id="orderForm">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-6">
          <div class="form-group font-weight-bold">
            {{ form.status|as_crispy_field }}
          </div>
          {{ form.production_status|as_crispy_field }}
          <div class="form-group font-weight-bold">
            {{ form.deadline|as_crispy_field }}
          </div>
          <div class="form-group">
            {{ form.internal_deadline|as_crispy_field }}
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group font-weight-bold">
            {{ form.partner|as_crispy_field }}
          </div>
          <div class="form-group font-weight-bold">
            {{ form.end_user|as_crispy_field }}
          </div>
          <div class="form-group font-weight-bold">
            {{ form.direct_customer|as_crispy_field }}
          </div>
          <div class="form-group font-weight-bold" id="onHoldReasonField" style="display: none;">
            {{ form.on_hold_reason|as_crispy_field }}
          </div>
        </div>
      </div>
      <button type="submit" class="btn btn-primary">Create</button>
    </form>
  </div>
  {% block extra_js %}
    
    <script src="{% static 'JavaScript/order_create_reason.js' %}"></script>
    <script src="{% static 'JavaScript/order_deadline.js' %}"></script>

  {% endblock %}
{% endblock %}

templates/sales/order_list.html
{% extends "layouts/base.html" %}
{% block content %}
  <div class="container">
    <h1 class="mt-5">Order List</h1>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Orders</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <form class="form-inline my-2 my-lg-0" method="GET" action=".">
              <input class="form-control mr-sm-2" type="search" placeholder="Search by number" aria-label="Search" name="search" value="{{ request.GET.search }}">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </li>
        </ul>
        <a href="{% url 'sale:order_create' %}" class="btn btn-primary">Create Order</a>
      </div>
    </nav>
    <table class="table table-bordered table-striped mt-3">
      <thead>
      <tr>
        <th>Number</th>
        <th>Status</th>
        <th>Production Status</th>
        <th>Created At</th>
        <th>Deadline</th>
        <th>Internal Deadline</th>
        <th>Updated At</th>
        <th>Partner</th>
        <th>End User</th>
        <th>Direct Customer</th>
        <th>On Hold Reason</th>
      </tr>
      </thead>
      <tbody>
      {% for order in page_obj %}
        <tr>
          <td>{{ order.number }}</td>
          <td>{{ order.status }}</td>
          <td>{{ order.production_status }}</td>
          <td>{{ order.created_at }}</td>
          <td>{{ order.deadline }}</td>
          <td>{{ order.internal_deadline }}</td>
          <td>{{ order.updated_at }}</td>
          <td>{{ order.partner }}</td>
          <td>{{ order.end_user }}</td>
          <td>{{ order.direct_customer }}</td>
          <td>{{ order.on_hold_reason }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    <div class="pagination-container">
      <nav aria-label="Page navigation">
        <ul class="pagination">
          {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page=1{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}" aria-label="First">
                <span aria-hidden="true">&laquo;&laquo;</span>
              </a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
          {% endif %}
          {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
              <li class="page-item active"><span class="page-link">{{ num }}</span></li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
              <li class="page-item"><a class="page-link" href="?page={{ num }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">{{ num }}</a></li>
            {% endif %}
          {% endfor %}
          {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}" aria-label="Last">
                <span aria-hidden="true">&raquo;&raquo;</span>
              </a>
            </li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </div>
{% endblock %}